Hero1=input("Enter hero1 name")
H1=int(input("no.of hit movies"))
A1=int(input("no.of average movies"))
F1=int(input("no.of flop movies"))
Hero2=input("Enter hero2 name")
H2=int(input("no.of hit movies"))
A2=int(input("no.of average movies"))
F2=int(input("no.of flop movies"))
P1=H1*10+A1*5+F1*(-5)
P2=H2*10+A2*5+F2*(-5)
print(Hero1) if P1>P2 else print(Hero2)
